### PR TITLE
Add wn-editor as extra package

### PR DESCRIPTION
**Pull request by Hypercookie**
This merge request adds `wn-editor` as an extra package as discussed in #17.
You can find more information about `wn-editor` [here](https://github.com/Hypercookie/wn-editor).

If any changes to `wn-editor` are required to merge this, please let me know and I will fix them as soon as possible.

Thanks for the good work!

### CODE REVIEW

**Comment by Hypercookie** [comment]
@goodmami 
I dont want to pressure you! Just asking if this will be possible at all. 
Thanks!

**Comment by goodmami** [comment]
Sorry, you were right to remind me. I've been sitting on this too long. I've now tested this and there were no issues installing the package. I'll merge the PR.

As a note (perhaps to myself for later), I'm having some second thoughts about using the extras mechanism for installing this. I offered in #17 to use the extra as a way of increasing visibility, but a call-out in the Wn's README would work just as well, or better. Extras, I think, normally install things that enable some optional functionality in the main package instead of another tool (that is, optional dependencies instead of dependents). We can revisit this decision later, e.g., for a 1.0 release.

**Comment by goodmami** [comment]
The failing lint test was not due to this PR. I'll fix it separately.

**Comment by Hypercookie** [comment]
Thanks for merging! 
I will keep wn-editor up to date. If anything comes up just ping me somewhere and we will discuss!

**Pull request merged**
