### PR TITLE
Draft of guides/wordnet

### PR DESCRIPTION
**Pull request by yoyo-go**
Update the draft version

### CODE REVIEW

**Review by goodmami — CHANGES_REQUESTED** [review]
I have a few comments below, but also in general:

* Can we make the SVGs use CSS classes to select the line color? They are almost illegible when a user has enabled dark mode (the documentation theme automatically chooses a dark theme based on user preferences).
* It would be great to link the words to the OMW or to the English Wordnet.

**Comment by yoyo-go** [comment]
I have made a commit to update the draft with below highlights:

- For the dark mode display, I have tested on both browser dark mode and Windows OS dark theme, the SVGs work good in my device, so I do not know what kind of dark mode cause the problem, but I add a background layer in the SVGs so that no matter what your theme color is, the SVG will show with a fixed background color.
- For the links, the RST formatting doesn't support nested style, I cannot make a word both superscribed and linked, so I think putting the links in the SVGs is better, I link all the words and relations in the SVGs. 

The Other Information section and word changes of previous feedback have been updated, I am still not quite sure with the Other Information section, I read the CILI: the Collaborative Interlingual Index paper, especially the WordNet Schema section and get some info from this paper, but apart from definition, example and metadata, the WordNet schema contains much more than the three, do we need to introduce all other items in the schema? I think just introducing the three may not guide the user to the whole picture of a wordnet.

**Comment by goodmami** [comment]
@yoyo-go thanks! It looks a bit better. The background color of the SVGs isn't ideal but it does make it legible, so it's good for now. There are a few more issues but I think it's easier if I fix them myself.

**Comment by goodmami** [comment]
Ok I'll fix the English wording issues, but for the SVG issue try this: https://stackoverflow.com/a/50152040/1441112

It won't be a "figure" anymore so it won't have a caption, and you may need to find another way to adjust the size, but it embeds the SVG directly so the links are clickable.

**Comment by yoyo-go** [comment]
Hi Michael, below format changes have been made:
1. Links in SVGs can open directly;
2. SVGs can auto switch to dark mode now;

**Comment by goodmami** [comment]
I think I will merge this now and then fix some remaining issues. Thanks for your work!

**Pull request merged**
