### PR TITLE
download: Add outpt_file optional parameter

### PR DESCRIPTION
**Pull request by fushinari**
This is specifically to accommodate my use case in https://github.com/fushinari/wordbook/pull/13 but can be used for other purposes as well. The purpose is to redirect all printing to the specified `output_file` without having to capture all of `sys.stderr`, which is not a thread-safe solution.

Also added exception handling when the file size is unknown as of the download failure.

On an unrelated note, I have two doubts.
- What are the equivalents to the old module's `antonyms()`, `also_sees()` and `similar_tos()`? I can't seem to find them.
- Why does the building of the database take so long? Is there any way to speed it up? It took more than an hour for building the ewn database in my case. That seems way too long for normal use. An easy way out seems to be to simple redistribute the `wn.db` file but I'd like to avoid that.

Btw, thanks for the work! Much better to interact with than the previous versions in general and I like the fact that the user gets to download the dictionary he requires. My only real gripe is with the time for building database itself. Other than that, it's pretty much perfect imo. :)

### CODE REVIEW

**Comment by goodmami** [comment]
Hi, thanks for this. In general I think it's a good idea to be able to redirect the progress output, and maybe even hook into a callback or something. I wasn't anticipating GUI applications using Wn as a backend. Let me think a bit on the PR before merging.

Regarding your questions, I've moved them to #68 and #69 so I don't lose track of the conversations.

> Btw, thanks for the work! Much better to interact with than the previous versions in general and I like the fact that the user gets to download the dictionary he requires. My only real gripe is with the time for building database itself. Other than that, it's pretty much perfect imo. :)

Many thanks for the kind words! The project is still forming and adapting so hopefully it can suit your needs better in the next release.

**Comment by fushinari** [comment]
> Hi, thanks for this. In general I think it's a good idea to be able to redirect the progress output, and maybe even hook into a callback or something. I wasn't anticipating GUI applications using Wn as a backend. Let me think a bit on the PR before merging.

Sure, take your time and it's fine to reject if you find a better approach too.

I was originally using the older wn module mostly as a temporary solution until I got time to work on using the database directly. But then I saw this and I felt like it would do everything I wanted it to. So I decided to try this instead.

**Comment by goodmami** [comment]
One more thing: if building the DB is really an issue, then maybe it would be fine for your app to distribute a pre-built `wn.db` file and to pin the Wn version. I don't want to do that for Wn proper because, at least for now, the database schema may change.

**Comment by fushinari** [comment]
Yes, I'm considering it. But I'm not in a hurry because the application itself has many other issues that I want to work on in the meantime. And during that time, I want to experiment with reducing the build time if possible. Thankfully you've made a lot of this easy for me, especially by allowing configuring the wn data directory. Much appreciated for use cases like mine.

**Comment by goodmami** [comment]
@fushinari what do you think about a callback function for updating the progress bar? That way you don't have to capture the printed stream at all and can make your own GTK-based one? For the other messages ("Cached file found", etc.), I could use the standard logging tools instead of prints. This would make it easier to silence, at least.

**Comment by fushinari** [comment]
So, if I'm understanding correctly, the callback function would get called only in the ProgressBar objects? Sounds good, much better than what I was doing. Maybe it should return a list or dictionary with the progress and the current status (as in, "building" or "downloading") ?

**Comment by goodmami** [comment]
I mean so you could provide your own update function and sidestep the `ProgressBar` class entirely. I'd need to refine the behavior a bit so the callback is called with initialization parameters. E.g.:

```pycon
>>> def my_update(n: int, **kwargs):
...     print('Callback:', n, kwargs)
...
>>> wn.download(url, callback=my_update)
Callback 0 {'max': 104288, 'unit': 'bytes'}
Callback: 8096 {}
Callback: 8096 {}
...
```

The `**kwargs` can also be used to provide some kind of status. E.g., during database building it specifies the `type`, i.e., the table being populated (words, senses, synsets, etc.). I do this by calling the `update()` method with an increment of 0 (so the bar doesn't change) and a new `type` value. The `ProgressBar` class uses this to update the string it displays.

https://github.com/goodmami/wn/blob/be274eda62316622f6bb0e548b5e2a6834dc216a/wn/_db.py#L291

**Comment by fushinari** [comment]
> I mean so you could provide your own update function and sidestep the ProgressBar class entirely.

That makes sense. I don't know why I assumed otherwise. :sweat_smile: 

> during database building it specifies the type

Oh. So, type would be None if it's a download and would be a string if building. That's good.

**Comment by goodmami** [comment]
> Oh. So, type would be None if it's a download and would be a string if building. That's good.

What kwargs are available depends on the function calling the callback. So for download there won't be a `type` key in the kwargs at all.

Anyway if you like this approach (for which I've created #70), then you or I can close this PR. Sorry that your contribution wouldn't make it to the Git history, but I appreciate your work which inspired the other approach.

**Comment by fushinari** [comment]
> Sorry that your contribution wouldn't make it to the Git history, but I appreciate your work which inspired the other approach.

No worries at all. Your approach is better in every way and will also help me reduce complexity in my application. Thank you for your concern :)

**Pull request closed without merging**
